apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv-PV_NAME
spec:
  capacity:
    storage: PV_SIZE
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: PV_PATH